### PR TITLE
add cairo and imagemagick information to debugging

### PR DESCRIPTION
**Pull request by jimthedev**
Cairo and Imagemagick must be installed on your system for shots to function correctly.

### CODE REVIEW

**Comment by bettse** [comment]
on OS X, I think the package needed is `graphicsmagick`, since it contains the `gm` command, which the `imagemagick` package does not appear to have.

**Comment by jimthedev** [comment]
Are you using brew install imagemagick? It worked for me on El Capitan

**Comment by bettse** [comment]
yeah, version 6.9.2-7 it appears from `brew info` (also on El Cap).  From an `ls` of `/usr/local/Cellar/imagemagick/6.9.2-7/bin`, it doesn't look like a `gm` binary is installed for me, was it for you?

`Magick++-config*  Magick-config*  MagickCore-config*  MagickWand-config*  Wand-config*  animate*  compare*  composite*  conjure*  convert*  display*  identify*  import*  mogrify*  montage*  stream*`

Did you use any custom --with-\* flags?  Seems so strange to see this difference.

**Comment by bevacqua** [comment]
Either should work

**Comment by gorkem-cetin** [comment]
Confirmed for Ubuntu 14.04

**Pull request merged**
